version: "3.9"
services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build:
      args:
      - DATABASE_URL
      - PROJECT_NAME
      - SECRET_KEY
      - ANPR_API_ENDPOINT
      - ANPR_API_USER
      - ANPR_API_PASSWORD
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/vlpr_app

volumes:
  postgres_data:
