services:
  db:
    container_name: db
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload
    volumes:
      - .:/license_plate_recognition_app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
